//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanteDB.Cdss.Xml.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CdssTranspileErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CdssTranspileErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SanteDB.Cdss.Xml.i18n.CdssTranspileErrors", typeof(CdssTranspileErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment operation is missing target path.
        /// </summary>
        internal static string ASSIGN_MISSING_PATH {
            get {
                return ResourceManager.GetString("ASSIGN_MISSING_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unclosed braces detected in expression {0}.
        /// </summary>
        internal static string CDSS_EXPRESSION_BRACE_EXPECTED {
            get {
                return ResourceManager.GetString("CDSS_EXPRESSION_BRACE_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computation is missing for logic element.
        /// </summary>
        internal static string COMPUTATION_MISSING {
            get {
                return ResourceManager.GetString("COMPUTATION_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Expression {0} is invalid - unknown symbol {1}.
        /// </summary>
        internal static string CSHARP_EXPRESSION_UNKNOWN_SYMBOL {
            get {
                return ResourceManager.GetString("CSHARP_EXPRESSION_UNKNOWN_SYMBOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computation expression cannot be assigned to context {0}.
        /// </summary>
        internal static string EXPRESSION_CANNOT_BE_APPLIED_IN_CONTEXT {
            get {
                return ResourceManager.GetString("EXPRESSION_CANNOT_BE_APPLIED_IN_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element: &apos;having type&apos; must be drawn from known primitives (int, bool, long, real, date, or string).
        /// </summary>
        internal static string FACT_UNKNOWN_PRIMITIVE_TYPE {
            get {
                return ResourceManager.GetString("FACT_UNKNOWN_PRIMITIVE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find resource type {0}.
        /// </summary>
        internal static string INVALID_CLASS_REF {
            get {
                return ResourceManager.GetString("INVALID_CLASS_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing C# Logic (hint: csharp(&quot;C# EXPRESSION&quot;)).
        /// </summary>
        internal static string MISSING_CSHARP_EXPRESSION {
            get {
                return ResourceManager.GetString("MISSING_CSHARP_EXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data block is missing content (example: data &quot;name&quot; as 
        ///$$ 
        ///CSV_DATA_HERE 
        ///$$ 
        ///end data.
        /// </summary>
        internal static string MISSING_DATA_TOKEN {
            get {
                return ResourceManager.GetString("MISSING_DATA_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing HDSI Logic (hint: hdsi(&quot;HDSI_EXPRESSION&quot;)).
        /// </summary>
        internal static string MISSING_HDSI_EXPRESSION {
            get {
                return ResourceManager.GetString("MISSING_HDSI_EXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;having id&apos; missing identifier (example: having id &lt;IDENTIFIER&gt;).
        /// </summary>
        internal static string MISSING_ID_TOKEN {
            get {
                return ResourceManager.GetString("MISSING_ID_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include statement is missing identifier or name.
        /// </summary>
        internal static string MISSING_INCLUDE_TARGET {
            get {
                return ResourceManager.GetString("MISSING_INCLUDE_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element: raise must carry a string or multi-line string with text for the issue.
        /// </summary>
        internal static string MISSING_ISSUE_TEXT {
            get {
                return ResourceManager.GetString("MISSING_ISSUE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element missing name token (hint: use &quot;name&quot; to identify the object).
        /// </summary>
        internal static string MISSING_NAME_TOKEN {
            get {
                return ResourceManager.GetString("MISSING_NAME_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;having oid&apos; missing oid token (hint: having oid &quot;1.2.3.4.5&quot;).
        /// </summary>
        internal static string MISSING_OID_TOKEN {
            get {
                return ResourceManager.GetString("MISSING_OID_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query instruction missing required parameters.
        /// </summary>
        internal static string MISSING_QUERY_PARAMETERS {
            get {
                return ResourceManager.GetString("MISSING_QUERY_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element: having scope must carry name or named id (example: having scope &lt;org.santedb.cdss....&gt;).
        /// </summary>
        internal static string MISSING_SCOPE_ID {
            get {
                return ResourceManager.GetString("MISSING_SCOPE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;having status&apos; missing status (hint: having status (active, dont-use or trial)).
        /// </summary>
        internal static string MISSING_STATUS_TOKEN {
            get {
                return ResourceManager.GetString("MISSING_STATUS_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;having uuid&apos; missing UUID (example: having uuid &quot;7C3F1AB1-A582-4920-BA3D-FC5E7B5D6F61&quot;).
        /// </summary>
        internal static string MISSING_UUID_TOKEN {
            get {
                return ResourceManager.GetString("MISSING_UUID_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element: &apos;define model&apos; is missing model content (must be XML or JSON multi-line string).
        /// </summary>
        internal static string MODEL_MISSING_DEFINITION_DATA {
            get {
                return ResourceManager.GetString("MODEL_MISSING_DEFINITION_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple expressions in a fact computation must be contained in none(), any() or all().
        /// </summary>
        internal static string MULTI_EXPRESSION_MUST_BE_AGGREGATE {
            get {
                return ResourceManager.GetString("MULTI_EXPRESSION_MUST_BE_AGGREGATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue priority is unknown - valid values are: info, error, warn.
        /// </summary>
        internal static string UNKNOWN_ISSUE_PRIORITY {
            get {
                return ResourceManager.GetString("UNKNOWN_ISSUE_PRIORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model format &apos;{0}&apos; is unknown or unsupported in this context.
        /// </summary>
        internal static string UNKNOWN_MODEL_FORMAT {
            get {
                return ResourceManager.GetString("UNKNOWN_MODEL_FORMAT", resourceCulture);
            }
        }
    }
}
