<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Condition="'$(VersionNumber)' == ''">
		<VersionNumber>3.1-debug</VersionNumber>
	</PropertyGroup>
	<PropertyGroup>
		<TargetFrameworks>net10.0;net48;netstandard2.0</TargetFrameworks>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>SanteDB.Cdss.Xml</PackageId>
		<Title>SanteDB.Cdss.Xml</Title>
		<Version>$(VersionNumber)</Version>
		<Description>SanteDB Clinical Decision Support XML Protocoling Engine. Provides a descriptive way to express and execute clinical protocols</Description>
		<Authors>SanteSuite Contributors</Authors>
		<PackageTags>SanteDB</PackageTags>
		<RepositoryUrl>https://github.com/santedb/santedb-cdss</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<IncludeSymbols>true</IncludeSymbols>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<Product>SanteDB</Product>
		<Copyright>Copyright (C) 2015-2026 SanteSuite Contributors (See: NOTICES)</Copyright>
		<Company>SanteSuite Contributors</Company>
		<PackageIconUrl>http://santesuite.org/assets/img/logo.png</PackageIconUrl>
		<PackageProjectUrl>http://santesuite.org</PackageProjectUrl>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Model.old\*.cs" />
	</ItemGroup>

	<ItemGroup>
		<Antlr4 Include="Antlr\CdssLibrary.g4">
			<Visitor>true</Visitor>
			<Listener>false</Listener>
			<GAtn>true</GAtn>
			<Package>SanteDB.Cdss.Xml.Antlr</Package>
			<Error>false</Error>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<JavaExec>PATH</JavaExec>
		</Antlr4>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="Antlr\CdssLibrary.g4" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
		<PackageReference Include="Antlr4BuildTasks" Version="12.14.0" PrivateAssets="all" />
		<PackageReference Include="DynamicExpresso.Core" Version="2.17.2" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="Newtonsoft.Json" Version="[13.0.4,13.1)" />
    <PackageReference Include="SharpCompress" Version="[0.50.0,0.51)" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\SanteDB.licenseheader">
			<Link>SanteDB.licenseheader</Link>
		</None>
		<None Include="Doc\XmlDecisionSupport\index.md" />
	</ItemGroup>
	<Choose>
		<When Condition="$(SolutionName.Contains('-nuget'))">
			<ItemGroup>
				<PackageReference Include="SanteDB.Core.Api" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.Applets" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.Model" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Rest.Common" Version="$(VersionNumber)" />
			</ItemGroup>
		</When>
		<Otherwise>
			<ItemGroup>
				<ProjectReference Include="..\..\santedb-model\SanteDB.Core.Model\SanteDB.Core.Model.csproj" />
				<ProjectReference Include="..\..\santedb-api\SanteDB.Core.Api\SanteDB.Core.Api.csproj" />
				<ProjectReference Include="..\..\santedb-applets\SanteDB.Core.Applets\SanteDB.Core.Applets.csproj" />
				<ProjectReference Include="..\..\santedb-restsvc\SanteDB.Rest.Common\SanteDB.Rest.Common.csproj" />
			</ItemGroup>
		</Otherwise>
	</Choose>
	<ItemGroup>
		<Compile Update="i18n\CdssTranspileErrors.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>CdssTranspileErrors.resx</DependentUpon>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Update="i18n\CdssTranspileErrors.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>CdssTranspileErrors.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
		<None Update="Schema\Cdss.xsd">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>